### ISSUE TITLE
Errors when building colloquy.cpp

### ISSUE THREAD

**Issue by roder** [wired/colloquypush#1]
I was trying to build the ZNC module, but it fails.  Any idea?

Here's the output from my Ubuntu Hardy server:
http://pastie.org/610556

**Comment by roder** [comment]
Fixed this issue after building ZNC from source

**Comment by wired** [comment]
This module was tested with the latest version of znc, 0.074 :) Ubuntu Hardy probably has an older version, thats why building from source fixed it.
