### ISSUE TITLE
logging of private messages

### ISSUE THREAD

**Issue by Bgamsa** [wired/colloquypush#12]
I'm correctly receiving notification for private messages, but they don't seem to be buffered, so that I don't get them in colloquy when I reconnect.  As a result, I can lose messages if there are multiple of them while I'm away, or if they are truncated when presented as a notification.  I don't know if anything similar happens for highlighted messages in non-private channels.

**Comment by wired** [comment]
does this happen with normal irc clients? this is probably not related to the colloquy module

**Comment by Bgamsa** [comment]
what I eventually found out is that this only happens if I have multiple clients connected at the same time (although I have only been using colloquy on all platforms).  However, I don't have the problem for non-private messages, so I'm guessing it's due to different rules about saving after delivery, since with only a single client, it's the case that I get the same buffer messages in regular channels on each connection (until I clear), but not in private channels.
