### ISSUE TITLE
device won't register for push

### ISSUE THREAD

**Issue by ninjudd** [wired/colloquypush#14]
I followed the instructions carefully, but when I do "/msg *colloquy list", it says:

```
*colloquy: You have no saved devices...
*colloquy: Connect to znc using your mobile colloquy client...
*colloquy: Make sure to enable push if it isn't already!
```

Push is enabled in Colloquy on my iPhone though, and the connection to ZNC works fine other than this problem.

I am running ZNC 0.093-2.svn2101.el5 on CentOS 5.4 if that matters.

**Comment by wired** [comment]
are you positive you have connected to znc with Colloquy with it's Push Notifications option enabled?

**Comment by ninjudd** [comment]
Sorry, should have closed this. It started working magically after a few days.

Thanks

**Comment by mattapperson** [comment]
I am seeing this issue too, and push is set to yes
