### ISSUE TITLE
Compile error on Fedora 13 with ZNC 0.093-2.svn2101.fc13 - http://znc.sourceforge.net

### ISSUE THREAD

**Issue by paeh** [wired/colloquypush#15]
Hello everyone,

I can't build the colloquy module with znc-buildmod (doesn't work with the repo version or the self-compiled versions of znc).
everything works two month ago...Don't know why it didn't work.

Did you have a idea why? If you know why it doesn't work, how i can fix this problem?

Thanks,
paeh

Building "colloquy.so"... colloquy.cpp:14:53: warning: missing terminating ' character
colloquy.cpp:14: error: missing terminating ' character
colloquy.cpp:46:27: warning: character constant too long for its type
colloquy.cpp:52:18: warning: character constant too long for its type
colloquy.cpp:52:33: warning: character constant too long for its type
colloquy.cpp:53:18: warning: character constant too long for its type
colloquy.cpp:55:41: warning: character constant too long for its type
colloquy.cpp:56:19: warning: character constant too long for its type
colloquy.cpp:56:60: warning: character constant too long for its type
colloquy.cpp:56:76: warning: character constant too long for its type
colloquy.cpp:56:92: warning: character constant too long for its type
colloquy.cpp:57:25: warning: character constant too long for its type
colloquy.cpp:57:34: warning: multi-character character constant
colloquy.cpp:73:42: warning: character constant too long for its type
colloquy.cpp:73:91: warning: character constant too long for its type
colloquy.cpp:73:114: warning: character constant too long for its type
colloquy.cpp:76:14: warning: character constant too long for its type
colloquy.cpp:76:47: warning: character constant too long for its type
colloquy.cpp:140:44: warning: multi-character character constant
colloquy.cpp:200: error: stray ‘#’ in program
colloquy.cpp:322:29: warning: character constant too long for its type
colloquy.cpp:323:29: warning: character constant too long for its type
colloquy.cpp:325:25: warning: character constant too long for its type
colloquy.cpp:383:96: error: invalid suffix "d0616df9b90035fe1" on integer constant
colloquy.cpp:1268:54: warning: multi-character character constant
colloquy.cpp:1268:64: warning: multi-character character constant
colloquy.cpp:1268:705: warning: multi-character character constant
colloquy.cpp:1268:715: warning: multi-character character constant
colloquy.cpp:1268:743: warning: multi-character character constant
colloquy.cpp:1268:753: warning: multi-character character constant
colloquy.cpp:1268: error: stray ‘#’ in program
colloquy.cpp:1268:816: warning: multi-character character constant
colloquy.cpp:1268:826: warning: multi-character character constant
colloquy.cpp:1268: error: stray ‘#’ in program
colloquy.cpp:1268:891: warning: multi-character character constant
colloquy.cpp:1268:901: warning: multi-character character constant
colloquy.cpp:1268: error: stray ‘#’ in program
colloquy.cpp:1268:966: warning: multi-character character constant
colloquy.cpp:1268:976: warning: multi-character character constant
colloquy.cpp:1268: error: stray ‘#’ in program
colloquy.cpp:1268:1044: warning: multi-character character constant
colloquy.cpp:1268:1054: warning: multi-character character constant
colloquy.cpp:1268: error: stray ‘#’ in program
colloquy.cpp:1268:1125: warning: multi-character character constant
colloquy.cpp:1268:1135: warning: multi-character character constant
colloquy.cpp:1268:1164: warning: multi-character character constant
colloquy.cpp:1268:1174: warning: multi-character character constant
colloquy.cpp:1268: error: stray ‘#’ in program
colloquy.cpp:1268:1243: warning: multi-character character constant
colloquy.cpp:1268:1253: warning: multi-character character constant
colloquy.cpp:1268:1282: warning: multi-character character constant
colloquy.cpp:1268:1292: warning: multi-character character constant
colloquy.cpp:1268:1401: warning: multi-character character constant
colloquy.cpp:1268:1411: warning: multi-character character constant
colloquy.cpp:1268:1488: warning: multi-character character constant
colloquy.cpp:1268:1498: warning: multi-character character constant
colloquy.cpp:1268:1831: warning: multi-character character constant
colloquy.cpp:1268:1841: warning: multi-character character constant
colloquy.cpp:1268:2136: warning: multi-character character constant
colloquy.cpp:1268:2146: warning: multi-character character constant
colloquy.cpp:1268:2279: warning: multi-character character constant
colloquy.cpp:1268:2289: warning: multi-character character constant
colloquy.cpp:1268:2425: warning: multi-character character constant
colloquy.cpp:1268:2435: warning: multi-character character constant
colloquy.cpp:1268:2569: warning: multi-character character constant
colloquy.cpp:1268:2579: warning: multi-character character constant
colloquy.cpp:1268:2628: warning: multi-character character constant
colloquy.cpp:1268:2638: warning: multi-character character constant
colloquy.cpp:1268:2667: warning: multi-character character constant
colloquy.cpp:1268:2677: warning: multi-character character constant
colloquy.cpp:1268:2838: warning: multi-character character constant
colloquy.cpp:1268:2848: warning: multi-character character constant
colloquy.cpp:1268:2877: warning: multi-character character constant
colloquy.cpp:1268:2887: warning: multi-character character constant
colloquy.cpp:1268:3134: warning: multi-character character constant
colloquy.cpp:1268:3144: warning: multi-character character constant
colloquy.cpp:1268:3335: warning: multi-character character constant
colloquy.cpp:1268:3345: warning: multi-character character constant
colloquy.cpp:1268:3394: warning: multi-character character constant
colloquy.cpp:1268:3404: warning: multi-character character constant
colloquy.cpp:1268:3433: warning: multi-character character constant
colloquy.cpp:1268:3443: warning: multi-character character constant
colloquy.cpp:1268:3719: warning: multi-character character constant
colloquy.cpp:1268:3729: warning: multi-character character constant
colloquy.cpp:1268:4061: warning: multi-character character constant
colloquy.cpp:1268:4071: warning: multi-character character constant
colloquy.cpp:1268:4120: warning: multi-character character constant
colloquy.cpp:1268:4130: warning: multi-character character constant
colloquy.cpp:1268:4159: warning: multi-character character constant
colloquy.cpp:1268:4169: warning: multi-character character constant
colloquy.cpp:1268:4445: warning: multi-character character constant
colloquy.cpp:1268:4455: warning: multi-character character constant
colloquy.cpp:1268:4686: warning: multi-character character constant
colloquy.cpp:1268:4696: warning: multi-character character constant
colloquy.cpp:1268:4888: warning: multi-character character constant
colloquy.cpp:1268:4898: warning: multi-character character constant
colloquy.cpp:1268:4927: warning: multi-character character constant
colloquy.cpp:1268:4937: warning: multi-character character constant
colloquy.cpp:1268:5047: warning: multi-character character constant
colloquy.cpp:1268:5057: warning: multi-character character constant
colloquy.cpp:1268:5107: warning: multi-character character constant
colloquy.cpp:1268:5117: warning: multi-character character constant
colloquy.cpp:1268:5146: warning: multi-character character constant
colloquy.cpp:1268:5156: warning: multi-character character constant
colloquy.cpp:1268:5265: warning: multi-character character constant
colloquy.cpp:1268:5275: warning: multi-character character constant
colloquy.cpp:1268:5324: warning: multi-character character constant
colloquy.cpp:1268:5334: warning: multi-character character constant
colloquy.cpp:1268:5363: warning: multi-character character constant
colloquy.cpp:1268:5373: warning: multi-character character constant
colloquy.cpp:1268:5504: warning: multi-character character constant
colloquy.cpp:1268:5514: warning: multi-character character constant
colloquy.cpp:1268:5681: warning: multi-character character constant
colloquy.cpp:1268:5691: warning: multi-character character constant
colloquy.cpp:1268:5720: warning: multi-character character constant
colloquy.cpp:1268:5730: warning: multi-character character constant
colloquy.cpp:1268:6131: warning: multi-character character constant
colloquy.cpp:1268:6141: warning: multi-character character constant
colloquy.cpp:1268:6303: warning: multi-character character constant
colloquy.cpp:1268:6313: warning: multi-character character constant
colloquy.cpp:1268:6423: warning: multi-character character constant
colloquy.cpp:1268:6433: warning: multi-character character constant
colloquy.cpp:1268:6483: warning: multi-character character constant
colloquy.cpp:1268:6493: warning: multi-character character constant
colloquy.cpp:1268:6522: warning: multi-character character constant
colloquy.cpp:1268:6532: warning: multi-character character constant
colloquy.cpp:1268:6801: warning: multi-character character constant
colloquy.cpp:1268:6811: warning: multi-character character constant
colloquy.cpp:1268:6919: warning: multi-character character constant
colloquy.cpp:1268:6929: warning: multi-character character constant
colloquy.cpp:1268:6978: warning: multi-character character constant
colloquy.cpp:1268:6988: warning: multi-character character constant
colloquy.cpp:1268:7017: warning: multi-character character constant
colloquy.cpp:1268:7027: warning: multi-character character constant
colloquy.cpp:1268:7751: warning: multi-character character constant
colloquy.cpp:1268:7761: warning: multi-character character constant
colloquy.cpp:1268:7971: warning: multi-character character constant
colloquy.cpp:1268:7981: warning: multi-character character constant
colloquy.cpp:1268:9113: warning: multi-character character constant
colloquy.cpp:1268:9123: warning: multi-character character constant
colloquy.cpp:1268:9233: warning: multi-character character constant
colloquy.cpp:1268:9243: warning: multi-character character constant
colloquy.cpp:1268:9293: warning: multi-character character constant
colloquy.cpp:1268:9303: warning: multi-character character constant
colloquy.cpp:1268:9332: warning: multi-character character constant
colloquy.cpp:1268:9342: warning: multi-character character constant
colloquy.cpp:1268:9632: warning: multi-character character constant
colloquy.cpp:1268:9642: warning: multi-character character constant
colloquy.cpp:1268:9806: warning: multi-character character constant
colloquy.cpp:1268:9816: warning: multi-character character constant
colloquy.cpp:1268:9866: warning: multi-character character constant
colloquy.cpp:1268:9876: warning: multi-character character constant
colloquy.cpp:1268:9905: warning: multi-character character constant
colloquy.cpp:1268:9915: warning: multi-character character constant
colloquy.cpp:1268:10027: warning: multi-character character constant
colloquy.cpp:1268:10037: warning: multi-character character constant
colloquy.cpp:1268:10066: warning: multi-character character constant
colloquy.cpp:1268:10076: warning: multi-character character constant
colloquy.cpp:1268:10209: warning: multi-character character constant
colloquy.cpp:1268:10219: warning: multi-character character constant
colloquy.cpp:1268:10248: warning: multi-character character constant
colloquy.cpp:1268:10258: warning: multi-character character constant
colloquy.cpp:1268:10789: warning: multi-character character constant
colloquy.cpp:1268:10799: warning: multi-character character constant
colloquy.cpp:1268:10828: warning: multi-character character constant
colloquy.cpp:1268:10838: warning: multi-character character constant
colloquy.cpp:1268:11072: warning: multi-character character constant
colloquy.cpp:1268:11082: warning: multi-character character constant
colloquy.cpp:1268:11610: warning: multi-character character constant
colloquy.cpp:1268:11620: warning: multi-character character constant
colloquy.cpp:1268:11670: warning: multi-character character constant
colloquy.cpp:1268:11680: warning: multi-character character constant
colloquy.cpp:1316: error: stray ‘#’ in program
colloquy.cpp:1333: error: stray ‘\303’ in program
colloquy.cpp:1333: error: stray ‘\247’ in program
colloquy.cpp:1337: error: stray ‘\346’ in program
colloquy.cpp:1337: error: stray ‘\227’ in program
colloquy.cpp:1337: error: stray ‘\245’ in program
colloquy.cpp:1337: error: stray ‘\346’ in program
colloquy.cpp:1337: error: stray ‘\234’ in program
colloquy.cpp:1337: error: stray ‘\254’ in program
colloquy.cpp:1337: error: stray ‘\350’ in program
colloquy.cpp:1337: error: stray ‘\252’ in program
colloquy.cpp:1337: error: stray ‘\236’ in program
colloquy.cpp:1341: error: stray ‘\303’ in program
colloquy.cpp:1341: error: stray ‘\252’ in program
colloquy.cpp:1345: error: stray ‘\344’ in program
colloquy.cpp:1345: error: stray ‘\270’ in program
colloquy.cpp:1345: error: stray ‘\255’ in program
colloquy.cpp:1345: error: stray ‘\346’ in program
colloquy.cpp:1345: error: stray ‘\226’ in program
colloquy.cpp:1345: error: stray ‘\207’ in program
colloquy.cpp:1366: error: stray ‘\303’ in program
colloquy.cpp:1366: error: stray ‘\240’ in program
colloquy.cpp:1370: error: stray ‘\304’ in program
colloquy.cpp:1370: error: stray ‘\214’ in program
colloquy.cpp:1370: error: stray ‘\305’ in program
colloquy.cpp:1370: error: stray ‘\241’ in program
colloquy.cpp:1382: error: stray ‘\303’ in program
colloquy.cpp:1382: error: stray ‘\261’ in program
colloquy.cpp:1386: error: stray ‘\303’ in program
colloquy.cpp:1386: error: stray ‘\247’ in program
colloquy.cpp:1406: error: stray ‘\346’ in program
colloquy.cpp:1406: error: stray ‘\227’ in program
colloquy.cpp:1406: error: stray ‘\245’ in program
colloquy.cpp:1406: error: stray ‘\346’ in program
colloquy.cpp:1406: error: stray ‘\234’ in program
colloquy.cpp:1406: error: stray ‘\254’ in program
colloquy.cpp:1406: error: stray ‘\350’ in program
colloquy.cpp:1406: error: stray ‘\252’ in program
colloquy.cpp:1406: error: stray ‘\236’ in program
colloquy.cpp:1426: error: stray ‘\303’ in program
colloquy.cpp:1426: error: stray ‘\252’ in program
colloquy.cpp:1430: error: stray ‘\320’ in program
colloquy.cpp:1430: error: stray ‘\241’ in program
colloquy.cpp:1430: error: stray ‘\321’ in program
colloquy.cpp:1430: error: stray ‘\200’ in program
colloquy.cpp:1430: error: stray ‘\320’ in program
colloquy.cpp:1430: error: stray ‘\277’ in program
colloquy.cpp:1430: error: stray ‘\321’ in program
colloquy.cpp:1430: error: stray ‘\201’ in program
colloquy.cpp:1430: error: stray ‘\320’ in program
colloquy.cpp:1430: error: stray ‘\272’ in program
colloquy.cpp:1430: error: stray ‘\320’ in program
colloquy.cpp:1430: error: stray ‘\270’ in program
colloquy.cpp:1442: error: stray ‘\344’ in program
colloquy.cpp:1442: error: stray ‘\270’ in program
colloquy.cpp:1442: error: stray ‘\255’ in program
colloquy.cpp:1442: error: stray ‘\346’ in program
colloquy.cpp:1442: error: stray ‘\226’ in program
colloquy.cpp:1442: error: stray ‘\207’ in program
colloquy.cpp:1471:18: warning: character constant too long for its type
colloquy.cpp:1471:32: warning: character constant too long for its type
colloquy.cpp:1471:54: warning: character constant too long for its type
colloquy.cpp:7: error: expected unqualified-id before ‘<’ token
colloquy.cpp:23: error: ‘var’ does not name a type
colloquy.cpp:33: error: expected unqualified-id before ‘)’ token
colloquy.cpp:46: error: expected constructor, destructor, or type conversion before ‘.’ token
colloquy.cpp:47: error: expected unqualified-id before ‘<’ token
colloquy.cpp:52: error: expected constructor, destructor, or type conversion before ‘.’ token
colloquy.cpp:53: error: expected constructor, destructor, or type conversion before ‘.’ token
colloquy.cpp:54: error: expected ‘)’ before ‘{’ token
colloquy.cpp:59: error: expected unqualified-id before ‘)’ token
colloquy.cpp:60: error: expected unqualified-id before ‘<’ token
colloquy.cpp:72: error: ‘function’ does not name a type
colloquy.cpp:76: error: expected constructor, destructor, or type conversion before ‘(’ token
colloquy.cpp:76: error: expected constructor, destructor, or type conversion before ‘(’ token
colloquy.cpp:77: error: expected unqualified-id before ‘<’ token
colloquy.cpp:200: error: expected unqualified-id before ‘<’ token
colloquy.cpp:227: error: expected unqualified-id before ‘<’ token
colloquy.cpp:234: error: expected unqualified-id before ‘<’ token
colloquy.cpp:243: error: expected unqualified-id before ‘<’ token
colloquy.cpp:257: error: expected unqualified-id before ‘<’ token
colloquy.cpp:378: error: expected constructor, destructor, or type conversion before ‘;’ token
colloquy.cpp:378: error: expected unqualified-id before ‘<’ token
colloquy.cpp:379: error: expected constructor, destructor, or type conversion before ‘;’ token
colloquy.cpp:379: error: expected constructor, destructor, or type conversion before ‘;’ token
colloquy.cpp:379: error: expected constructor, destructor, or type conversion before ‘;’ token
colloquy.cpp:379: error: expected unqualified-id before ‘<’ token
colloquy.cpp:383: error: expected unqualified-id before ‘<’ token
colloquy.cpp:1268: error: expected constructor, destructor, or type conversion before ‘.’ token
colloquy.cpp:1268: error: expected unqualified-id before ‘<’ token
[ !! ] Error while building "colloquy.so"

**Comment by wired** [comment]
your module source file seems broken, try redownloading it

**Comment by paeh** [comment]
hey wired,

I've reloaded the colloquy.cpp but i still can't build the module.

the module src has the following sha256sum:

f77dba617db206b3d56425156a67f84096fa11bb0498828e49252bd2714b2908  colloquy.cpp

my znc version is:
ZNC 0.093-2.svn2101.fc13 - http://znc.sourceforge.net

my linux version is:
Linux 2.6.34.6-54.fc13.x86_64 #1 SMP Sun Sep 5 17:16:27 UTC 2010 x86_64 x86_64 x86_64 GNU/Linux

thanks,
paeh

**Comment by wired** [comment]
that sum is wrong, it should be

55c8e655e162cd025b3134266a8378fc02f532dddb058e1b9c9a5528f4520fb3  colloquy.cpp

are you sure you got the raw file?

http://github.com/wired/colloquypush/raw/master/znc/colloquy.cpp

**Comment by paeh** [comment]
now it works... thanks for your help :)

i always downloaded the version linked at the startpage:

colloquy.cpp    July 18, 2010   Fixed broken badge clear on awayonlypush [capi]
http://github.com/wired/colloquypush/blob/master/znc/colloquy.cpp

and this version won't work

thanks again,

paeh

<closed>
