### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by ghost** [wired/colloquypush#16]
I'm getting an error when attempting to compile

% znc-buildmod colloquy.cpp 
Building colloquy.so... colloquy.cpp: In member function ‘bool CColloquyMod::Push(const CString&, const CString&, const CString&, bool, int)’:
colloquy.cpp:655: error: ‘class CUser’ has no member named ‘IsIRCAway’
[ !! ] Error while building colloquy.so

distribution: Ubuntu 10.04.1 LTS
uname -a: Linux 2.6.32-25-generic #44-Ubuntu SMP Fri Sep 17 20:05:27 UTC 2010 x86_64 GNU/Linux

**Comment by wired** [comment]
what's your ZNC version?

**Comment by psychon** [comment]
IsIRCAway() was added in 0.074.

**Comment by JoeMaverickSett** [comment]
i also had this error in 0.0800 but then i upgraded to 0.094 and it no longer had that error.

**Comment by ghost** [comment]
I had the version that was packed with Ubuntu 10.04, which was znc-0.078. I guess the packaged version was the problem, I build 0.094 from source and it worked fine.

Thanks!
