### ISSUE TITLE
is there any way to compile colloquy.cpp without installing znc via source compile?

### ISSUE THREAD

**Issue by comfuture** [wired/colloquypush#18]
Hi. I'm using ubuntu 10.04.
there is znc apt package but znc-buildmod is not exists in it.
I can build znc via source tarball, but i think that's not cool way on ubuntu.

is there any way to compile colloquy.cpp without installing znc via source compile?

and another:
I'm often using znc on non-ascii-charset irc server like cp949, cp932...
colloquy module pushes notify well but breaks characters..
is there any way to convert server message to utf-8?
i'm happy to have some encoding options.

sorry for my poor english.
cheers.

**Comment by berle** [comment]
To get znc-buildmod on ubuntu, install znc-dev
