### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by joachimtingvold** [wired/colloquypush#27]
Trying to compile colloquypush, fails with the following error(s);

```
jocke@omg:~/diverse/znc/znc-0.205-install/bin$ ./znc-buildmod colloquy.cpp 
Building "colloquy.so" for ZNC 0.205... colloquy.cpp: In member function ‘virtual CModule::EModRet CColloquyMod::OnUserRaw(CString&)’:
colloquy.cpp:384: error: ‘class CUser’ has no member named ‘GetIRCServer’
colloquy.cpp:384: error: ‘class CUser’ has no member named ‘GetIRCNick’
colloquy.cpp: In member function ‘bool CColloquyMod::Push(const CString&, const CString&, const CString&, bool, int)’:
colloquy.cpp:716: error: ‘class CUser’ has no member named ‘IsIRCAway’
colloquy.cpp:763: error: ‘class CUser’ has no member named ‘GetClients’
colloquy.cpp:788: error: ‘class CUser’ has no member named ‘GetIRCNick’
[ !! ] Error while building "colloquy.so"
```

Any idea what's causing this?

I'm running znc 0.205 (compiled from source).

**Comment by joachimtingvold** [comment]
No one? :-/

**Comment by kylef** [comment]
@jallakim, this repository for colloquy push only supports stable version of ZNC. I have a branch on my fork of this module which adds compatibility for the git version of ZNC. See https://github.com/kylef/colloquypush/tree/1.0 the branch 1.0 on my repo.

**Comment by joachimtingvold** [comment]
@kylef, ahhh! Thanks. It compiled now. The IPv6-bindhost-issue in ZNC still doesn't seem to be solved. Meh. Have to do another round with debugging again :-(

**Comment by kylef** [comment]
@jallakim The DNS resolution should be fixed in the latest git version of ZNC which uses threaded DNS instead of c-ares. Are you using an older commit?

**Comment by joachimtingvold** [comment]
@kylef That was the sole reason for my above issue; I wanted to use ZNC from the git source, as it should've fixed the IPv6 bindhost-issue I reported ages ago. I'll do some debugging this weekend, I guess, as things doesn't seem to be fixed (or I'm doing something wrong). If I use a bindhost with IPv4, everything works, but if I change to an IPv6 bindhost, no traffic at all is seen using tcpdump.

**Comment by kylef** [comment]
Well, if you use a IPv6 bindhost it wont work because colloquy.mobi doesn't have an IPv6 address. What is fixed is that you don't need an IPv4 bindhost to make colloquy work, instead it will work an empty bindhost.

**Comment by joachimtingvold** [comment]
Well, the issue I created was marked as fixed due to those changes, which they are not if what you say is true. I know very well that colloquy.mobi doesn't have an IPv6-address; the issue is that it should use an IPv4-address (at least if the system has one available) to connect to colloquy.mobi (even if you use a IPv6 bindhost), and not just fail 'out of the blue' like this. I'd understand this behavior if the system was IPv6-only, though.

**Comment by zeamp** [comment]
Still no fix for the IPv6 bindhost issue as I write this. I have been working with the Colloquy developer in attempts to resolve this issue. With more people (and specifically IRC users) migrating to IPv6 for extended address space, I see this becoming more and more of an issue.
