### ISSUE TITLE
Not receiving notifications.

### ISSUE THREAD

**Issue by sduensin** [wired/colloquypush#3]
I've installed and enabled the module.  What I'd like to do is connect to ZNC from my desktop all the time as well as from my phone when I'm away from my desk.  When I do this, and someone mentions my nick, I do not get a push event on the phone.

Did I do something wrong, or am I misunderstanding the intent of this module?

Thanks!

**Comment by madmerry** [comment]
same here. hilights do not work but private messages work perfectly.
I did not have time to investigate more.
keep in touch

**Comment by wired** [comment]
By default, znc won't send notifications if a client is connected. Pass the argument "-attachedpush 1" to change that.

Or you could enable the idle option. I've set it to ten minutes, so if I forget my irssi open I get notifications after 10 minutes of inactivity.

**Comment by pencil** [comment]
I don't receive any push notifications (iPhone and iPad set up). Settings:

```
+-----------------------------------+-----------+
| Option                            | Value     |
+-----------------------------------+-----------+
| Push only if away                 | false     |
| Push even if clients are attached | true      |
| - only if idle for                | Always    |
|                                   |           |
| Night Hours (no push)             | --- - --- |
| Ignore network services           | false     |
+-----------------------------------+-----------+
```

Can I some how enable debugging to see where it hangs?
