### ISSUE TITLE
"You have no saved devices", after connecting Mobile Colloquy with push option on

### ISSUE THREAD

**Issue by 10p-freddo** [wired/colloquypush#33]
ZNC says "You have no saved devices..." when I do /msg *colloquy list
I have connected my Mobile Colloquy client to ZNC with the Push Notifications option enabled.
This is with commit 6aca83bfaf9c7d01f939ba2898d34c9c485aee22 running on ZNC 1.0.

**Comment by 10p-freddo** [comment]
Wow. This guy wasn't kidding when he said it magically starts working after a few days:
https://github.com/wired/colloquypush/issues/14

I just got the push notification authorization popup on my iPhone this morning, and now it works.

**Comment by duckydan** [comment]
Me and another guy found that if you force-exit the app on the mobile side, then re-open it, the pushes started right away. YMMV

**Comment by wired** [comment]
colloquy's service has some issues from time to time, glad to know it works for you now :)
