### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by thumphries** [wired/colloquypush#36]
Had some problems getting this to work, initially. Colloquy does its permissions check when it starts up - obviously its quite rare for apps to actually get killed on recent iPhones. So, it's possible to turn on push notifications and not get the permission toggled in iOS, leading to silent failures.

It doesn't request push notifications unless the flag is on in at least one of your connections when it starts up.

So, the module will fail silently if you turn on push without restarting Colloquy. (Hopefully this can be replicated, I just wasted quite a few hours learning this.) Perhaps this could be added to the setup section of the README?

i.e. just something like this

"Manually kill and restart Colloquy if your device is not automatically registered. Ensure Colloquy has been granted push notification privileges."

**Comment by wired** [comment]
done in https://github.com/wired/colloquypush/commit/989bb187106be43e8e9946e82bcd9f2177d13ae5

thanks :)
