### ISSUE TITLE
Loosing Buffer

### ISSUE THREAD

**Issue by martinfischer** [wired/colloquypush#4]
I'm not getting my buffers played back when I connect in the morning and colloquy module was active.

As argument i have only: -attachedpush 0
I have set nightime to 23:55 - 08:00. No idle time. 

I use savebuff and i do not keep buffers. I did not connect from the iphone app, before trying with mirc, I know this would delete the buffer.

When I connect in the morning I just get nothing played back now, this happens only with this module active. I will try tonight to deactivate push in the iphone app, but leave the module loaded.

**Comment by wired** [comment]
are you using the latest znc version? is this still an issue?

**Comment by martinfischer** [comment]
Sorry for the late answer. Issue seems to have been resolved.
