### ISSUE TITLE
Push only works with IPv4 connection

### ISSUE THREAD

**Issue by Dirk23** [wired/colloquypush#41]
When you have a IPv6 Internet Connection colloquy Push Modul connects through IPv6 to colloquy.mobi:7906 via IPv6, but the Service does not respond on IPv6 request, so Push is not working.
(Source: IRC Freenode -> #colloquy-mobile -> Operator "NoOneButMe")

**Comment by zadr** [comment]
colloquy.mobi:7906 should support ipv6 now

(source: i'm the guy who maintains the push server)
