### ISSUE TITLE
Option to Ignore Network Services

### ISSUE THREAD

**Issue by ianstalk** [wired/colloquypush#5]
Can you include an option to not push messages from network services (e.g. nickserv and chanserv)? Occasionally there'll be a netsplit on one of the networks I use and, when the servers resynchronize, chanserv will send an onjoin message. If I've been idle for a while, it gets pushed to my phone.

**Comment by wired** [comment]
I'll check it out :)

**Comment by adamcandy** [comment]
It's a hard-coded hack, but it works very nicely for me:

<pre>
<       CSocket *pSock = new CSocket(&m_Parent);
<       pSock->Connect(m_sHost, m_uPort, true);
<       pSock->Write(sPayload);
<       pSock->Close(Csock::CLT_AFTERWRITE);
<       m_Parent.AddSocket(pSock);
---
>       if ( (!sNick.empty()) and (!sNick.Equals("NickServ")) and (!sNick.Equals("ChanServ")) and (!sNick.Equals("MemoServ")) ) {
>           CSocket *pSock = new CSocket(&m_Parent);
>           pSock->Connect(m_sHost, m_uPort, true);
>           pSock->Write(sPayload);
>           pSock->Close(Csock::CLT_AFTERWRITE);
>           m_Parent.AddSocket(pSock);
>       }
</pre>

It wouldn't take much more to make this an option, or even to specify the strings.

**Comment by wired** [comment]
thanks adamcandy, I think I'll make it optional and add it to the module :)

**Comment by adamcandy** [comment]
Looking at the code again, that wasn't the best way to implement this - for one the badge clear wasn't working with this hack.  The check should go with the others.  Here's a patch to the current version of colloquy.cpp which adds an option to ignore network services with the option:
-ignorenetworkservices 1

<pre>
291a292
>       m_bIgnoreNetworkServices = false;
327a329,330
>           } else if ( sArg.TrimPrefix("ignorenetworkservices") ) {
>               m_bIgnoreNetworkServices = sArg.ToBool();
659a663,668
>       if ( m_bIgnoreNetworkServices ) {
>       if ( sNick.Equals("NickServ") or sNick.Equals("ChanServ") or sNick.Equals("MemoServ") ) {
>             return false;
>         }
>     }
> 
806a816
>   bool  m_bIgnoreNetworkServices;
</pre>

**Comment by adamcandy** [comment]
Further to this addition above, I have included options to push to Prowl as well - which can be handy when there are problems with Colloquy push.  It's all setup in *colloquy, just like the idle settings.

Currently pushing to Colloquy seems fine, but sometimes Prowl is more reliable.

Anyone interested in using this, or adding it to the repository?

**Comment by wired** [comment]
I've merged your ignorenetworkservices patch to the module.

pushing to prowl would be interesting as well. may I recommend forking colloquypush, committing the patch then sending me a pull request instead of pasting the patch here? :)

**Comment by adamcandy** [comment]
Thanks for the suggestion - I've finally got around to submitting the pull request.  I'd be interested in any suggestions to improve the implementation.  Thanks!
