### ISSUE TITLE
Build error on Ubuntu 9.10 x86_64

### ISSUE THREAD

**Issue by ulope** [wired/colloquypush#6]
Hi,

I get the following error while trying to build the znc module with the ubuntu supplied znc-buildmod:
http://dpaste.com/hold/144190/

**Comment by wired** [comment]
which version of znc?

**Comment by ulope** [comment]
Hi.
The version was the problem. It seems the ubuntu 9.10 supplied version is too old.
I recompiled znc from source and everything worked.

Sorry for the noise.

**Comment by wired** [comment]
no problem, glad you sorted it out :)
