### ISSUE TITLE
Build error on Debian squeeze/sid x86

### ISSUE THREAD

**Issue by dustin-lennon** [wired/colloquypush#8]
There was an update to the Debian znc package that I believe is causing issues when trying to compile this module with znc-buildmod.

Forgive me for some of the odd characters in what I'm about to paste.

fenrir:/home/znc# znc-buildmod colloquy.cpp                                     Building "colloquy.so"... In file included from /usr/include/znc/Socket.h:12,
                 from /usr/include/znc/Client.h:12,
                 from /usr/include/znc/znc.h:12,
                 from colloquy.cpp:9:
/usr/include/znc/Csocket.h:66:18: error: ares.h: No such file or directory
In file included from /usr/include/znc/Socket.h:12,
                 from /usr/include/znc/Client.h:12,
                 from /usr/include/znc/znc.h:12,
                 from colloquy.cpp:9:
/usr/include/znc/Csocket.h:989: error: âares_channelâ does not name a type
/usr/include/znc/Csocket.h:1039: error: âares_channelâ does not name a type
/usr/include/znc/Csocket.h: In member function âvirtual void TSocketManager<T>::Select(std::map<T*, TSocketManager<T>::EMessages, std::less<T*>, std::allocator<std::pair<T* const, TSocketManager<T>::EMessages> > >&)â:
/usr/include/znc/Csocket.h:1897: error: âares_channelâ was not declared in this scope
/usr/include/znc/Csocket.h:1897: error: expected â;â before âpChannelâ
/usr/include/znc/Csocket.h:1898: error: âpChannelâ was not declared in this scope
/usr/include/znc/Csocket.h:1900: error: there are no arguments to âares_fdsâ that depend on a template parameter, so a declaration of âares_fdsâ must be available
/usr/include/znc/Csocket.h:1900: note: (if you use â-fpermissiveâ, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/usr/include/znc/Csocket.h:1902: error: there are no arguments to âares_timeoutâ that depend on a template parameter, so a declaration of âares_timeoutâ must be available
/usr/include/znc/Csocket.h:2036: error: âares_channelâ was not declared in this scope
/usr/include/znc/Csocket.h:2036: error: expected â;â before âpChannelâ
/usr/include/znc/Csocket.h:2037: error: âpChannelâ was not declared in this scope
/usr/include/znc/Csocket.h:2038: error: there are no arguments to âares_processâ that depend on a template parameter, so a declaration of âares_processâ must be available
/usr/include/znc/Csocket.h: In member function âvoid TSocketManager<T>::Select(std::map<T*, TSocketManager<T>::EMessages, std::less<T*>, std::allocator<std::pair<T* const, TSocketManager<T>::EMessages> > >&) [with T = CZNCSock]â:
colloquy.cpp:783:   instantiated from here
/usr/include/znc/Csocket.h:1898: error: âares_fdsâ was not declared in this scope
/usr/include/znc/Csocket.h:1898: error: âares_timeoutâ was not declared in this scope
colloquy.cpp:783:   instantiated from here
/usr/include/znc/Csocket.h:2037: error: âares_processâ was not declared in this scope
[ !! ] Error while building "colloquy.so"

Thanks for the assistance if you are able to provide any.

**Comment by wired** [comment]
This usually happens because of an old znc version. Please try to get a newer package of znc (or build one yourself), then try to build the module again.

**Comment by dustin-lennon** [comment]
It is actually an updated version of ZNC. Version 0.080 has been released. Change log is here: http://en.znc.in/wiki/ChangeLog/0.080

I was running version ZNC 0.078

**Comment by dustin-lennon** [comment]
I'm guessing that since I see colloquy.cpp was updated a couple days ago, you are addressing changes in 0.080?

**Comment by datakurre** [comment]
Please, try installing libares-dev package (for missing ares.h).

**Comment by wired** [comment]
solved, thanks to datakurre for noticing
