### ISSUE TITLE
Loading module leads to ZNC refusing connections from Colloquy Mobile

### ISSUE THREAD

**Issue by sigwinch28** [wired/colloquypush#9]
after compiling the colloquy module using znc-buildmod and moving the module to ~/.znc/modules/

The connection via Colloquy works the first time, but then an issue arises when trying to connect again.

Colloquy can connect to ZNC, but disconnects almost immediately, and i get a message from *status telling me that another client has authenticated as my user. Colloquy displays my nick chosen in the app itself, then switches to my ZNC's nick, and then disconnects.

Upon unloading the module, this problem disappears and i can reconnect to ZNC from colloquy again.

I am using no non-standard modules with ZNC (0.078) and running on Gentoo x86.

**Comment by damz** [comment]
I'm seeing that too: loading this module on ZNC 0.078 (I'm running the version from Debian Lenny Backports) can prevent any client from successfully connecting. I haven't been able to identify the conditions needed to trigger this behavior, but I got that very frequently and unloading this module definitely fixes it.

**Comment by wired** [comment]
your znc version is pretty old. can you try with a newer, 0.09x one?
